require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/desks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Desk. As you add validations to Desk, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      room = FactoryBot.create(:room)
      10.times { FactoryBot.create(:desk, room: room)}
      get desks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      desk = Desk.create! valid_attributes
      get desk_url(desk)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_desk_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      desk = Desk.create! valid_attributes
      get edit_desk_url(desk)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Desk" do
        expect {
          post desks_url, params: { desk: valid_attributes }
        }.to change(Desk, :count).by(1)
      end

      it "redirects to the created desk" do
        post desks_url, params: { desk: valid_attributes }
        expect(response).to redirect_to(desk_url(Desk.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Desk" do
        expect {
          post desks_url, params: { desk: invalid_attributes }
        }.to change(Desk, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post desks_url, params: { desk: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested desk" do
        desk = Desk.create! valid_attributes
        patch desk_url(desk), params: { desk: new_attributes }
        desk.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the desk" do
        desk = Desk.create! valid_attributes
        patch desk_url(desk), params: { desk: new_attributes }
        desk.reload
        expect(response).to redirect_to(desk_url(desk))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        desk = Desk.create! valid_attributes
        patch desk_url(desk), params: { desk: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested desk" do
      desk = Desk.create! valid_attributes
      expect {
        delete desk_url(desk)
      }.to change(Desk, :count).by(-1)
    end

    it "redirects to the desks list" do
      desk = Desk.create! valid_attributes
      delete desk_url(desk)
      expect(response).to redirect_to(desks_url)
    end
  end
end
